### ISSUE TITLE
Not found page "Projects" and "About"

### ISSUE THREAD

**Issue by MellKam** [LWJerri/lwjerri.dev#1]
![image](https://user-images.githubusercontent.com/51422045/212027018-6afc4008-f278-477b-ac3e-9c8caa923443.png)

**Comment by LWJerri** [comment]
Hi. Yes, I am aware of this problem and am working on a solution.

**Comment by LWJerri** [comment]
Problem resolved. Big thanks to @Satont

Also, use https://www.lwjerri.dev/ <3
